services:
  - name: my-react-app  # Replace with your service name!
    type: static
    static:
      - root: ./build  # Serve files from the 'build' directory
        headers:
          Cache-Control: public, max-age=3600
      - root: ./build/*.js
        headers:
          Content-Type: text/javascript
      - root: ./build/*.css
        headers:
          Content-Type: text/css
      - root: ./build/assets # Example for assets like images
        headers:
          Content-Type: image/jpeg # Example for jpeg files
