services:
  - name: your-service-name  # Replace with your Render service name (important!)
    type: static
    static:
      - root: ./  # Or the path to your static files (e.g., ./build, ./dist, ./public)
        headers:
          Content-Type: text/javascript  # For JavaScript files
      - root: ./css  # Example for CSS files
        headers:
          Content-Type: text/css
      - root: ./assets # Example for assets like images
        headers:
          Content-Type: image/jpeg # Example for jpeg files
